name: Create and Publish docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
       
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: v3
          labels: myapp

  
      
