name: Create and Publish docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@main
       
      - name: Log in to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      
      - name: Build the Docker image
        run: docker build -t ${{secrets.docker_username}}/${{image_name}}:latest .
        
      - name: Tag the Docker image
        run: docker tag ${{secrets.docker_username}}/${{image_name}}:latest ${{secrets.docker_username}}/${{image_name}}:1.0
        
      - name: Push the Docker image to the registry
        run: docker push ${{secrets.docker_username}}/${{image_name}}:1.0

  
      
