name: Create and Publish docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@main
       
      - name: Log in to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@jenkins-maven-pipeline-project-41T
        with:
          images: ${{secrets.docker_username}}/${{inputs.image_name}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@jenkins-maven-pipeline-project-41T
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  
      
