name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repo
      - uses: actions/checkout@v2
      
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD    
         
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag supriyashevate/my-awesome-app:$(date +%s)
      
      - name: Push the Docker image
        run: docker push supriyashevate/my-awesome-app:$(date +%s)
