name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repo
      - uses: actions/checkout@v2
    
      - name: Log in to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-awesome-app:$(date +%s)
