name: User workflow 

on: 
  workflow_dispatch:

jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one line script
        run: echo "Hello from user workflow !!!"
  
  docker:
    uses: supriyashevate/reusableworkflow/.github/workflows/BuildAndPublishDockerImage.yml@main
    with:
      image_name: my-awesome-app
      tag: $(Build.BuildNumber)
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      

